### ISSUE TITLE
aem_conversion_configs should contain an explicit "fields" parameter

### ISSUE THREAD

**Issue by Sunrise17** [facebook/facebook-ios-sdk#1933]
### Checklist before submitting a bug report

- [X] I've updated to the latest released version of the SDK
- [X] I've searched for existing [GitHub issues](https://github.com/facebook/facebook-ios-sdk/issues)
- [X] I've looked for existing answers on [Stack Overflow](https://facebook.stackoverflow.com), the [Facebook Developer Community Forum](https://developers.facebook.com/community/) and the [Facebook Developers Group](https://www.facebook.com/groups/fbdevelopers)
- [X] I've read the [Code of Conduct](https://github.com/facebook/facebook-ios-sdk/blob/main/CODE_OF_CONDUCT.md)
- [X] This issue is not security related and can safely be disclosed publicly on GitHub

### Xcode version

13

### Facebook iOS SDK version

12.1.0

### Dependency Manager

CocoaPods

### SDK Framework

Login

### Goals

```
let fbLoginManager = LoginManager()
                
fbLoginManager.logIn(permissions: ["public_profile", "email"], from: self) { (result, error) in }
```

When i run the above function to start logIn process, xcode debug screen results following logs,

```
2021-11-08 23:40:15.642076+0300[6205:1066354] FBSDKLog: starting with Graph API v2.4, GET requests for /23876897821123120/aem_conversion_configs should contain an explicit "fields" parameter

2021-11-08 23:40:17.354519+0300[6205:1066096] -canOpenURL: failed for URL: "fbauth2:/" (OSStatus error -10814.)"
```

All 15 items including "fbauth2" have already been registered in LSApplicationQueriesSchemes as in [Facebook guide](https://developers.facebook.com/docs/facebook-login/ios).

### Expected results

There is no problem while logging in with Facebook account into the app, but finally these logs should not be seen in the debug area.

### Actual results

```
2021-11-08 23:40:15.642076+0300[6205:1066354] FBSDKLog: starting with Graph API v2.4, GET requests for /23876897821123120/aem_conversion_configs should contain an explicit "fields" parameter

2021-11-08 23:40:17.354519+0300[6205:1066096] -canOpenURL: failed for URL: "fbauth2:/" (OSStatus error -10814.)"
```

**Comment by Lisog** [comment]
same issue

**Comment by ahcfhy** [comment]
same issue in facebook shareing

**Comment by jawwad** [comment]
@Sunrise17, @Lisog, @ahcfhy - Thanks for reporting this. @KylinChang has added a fix for this with 96dcb78a721e44e6371212c0d553807d5afc3a99 which will be available in the v12.2.0 release.

**Comment by vipinsaini0** [comment]
Hi @jawwad @KylinChang , when it'll be available for us? I mean any release date of v12.2.0?

**Comment by vipinsaini0** [comment]
> @Sunrise17, @Lisog, @ahcfhy - Thanks for reporting this. @KylinChang has added a fix for this with [96dcb78](https://github.com/facebook/facebook-ios-sdk/commit/96dcb78a721e44e6371212c0d553807d5afc3a99) which will be available in the v12.2.0 release.

Hi @jawwad @KylinChang , when it'll be available for us? I mean any release date of v12.2.0?

**Comment by jawwad** [comment]
@vipinsaini0 - Probably early next week. Monday or Tuesday if there aren't any issues.

**Comment by jawwad** [comment]
This fix for this has been released today with v12.2.0!

**Comment by vipinsaini0** [comment]
> This fix for this has been released today with v12.2.0!

Thank you @jawwad for this update. 
But After update on 12.2.0, I'm not able to run(Build) the app (getting error - 113 duplicate symbols for architecture x86_64). 

https://github.com/facebook/facebook-ios-sdk/issues/1972#issue-1072976359

**Comment by MRGBB** [comment]
Hello, after I update the SDK to 12.2.0, this problem disappeared, but using a FBSDKShareDialogModeNative mode to share, I can jump to FBApp, but does not display the sharing feature edit page
