### ISSUE TITLE
"use of '@import' when C++ modules are disabled" errors when updating to 5.11.0

### ISSUE THREAD

**Issue by georgii11** [facebook/facebook-ios-sdk#1128]
I updated the SDK from 5.8.0 to 5.11.0 and I got a bunch of errors in some headers of the frameworks:

`FBSDKLoginKit.framework/Headers/FBSDKLoginButton.h:24:1: error: use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules
FBSDKShareKit.framework/Headers/FBSDKHashtag.h:24:1: error: use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules
FBSDKShareKit.framework/Headers/FBSDKShareOpenGraphObject.h:24:1: error: use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules
FBSDKShareKit.framework/Headers/FBSDKSharingContent.h:24:1: error: use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules
FBSDKShareKit.framework/Headers/FBSDKShareMessengerActionButton.h:24:1: error: use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules
`

It was all working fine without any modules before updating the Facebook frameworks (and that was the only change I did).

I noticed that where I get the errors, changes like the following were made:
1. replaced 
`#import <FBSDKCoreKit/FBSDKButton.h>

#import <FBSDKLoginKit/FBSDKLoginManager.h>
`
with 
`#ifdef BUCK
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#else
@import FBSDKCoreKit;
#endif

#import "FBSDKLoginManager.h"
`

2. replaced 
`#import <FBSDKCoreKit/FBSDKCopying.h>`
with: 
`#ifdef BUCK
#import <FBSDKCoreKit/FBSDKCoreKit.h>
#else
@import FBSDKCoreKit;
#endif
`

and more like that.

My project is mixed with objective-c and c++ and I found [here](https://stackoverflow.com/questions/29701647/use-of-import-when-modules-are-disabled/36307557#36307557) that the way those imports are made might be the issue.
What is that "BUCK" define? Would it be safe to add it in my project so that the imports are made like before with explicit path?

**Comment by joesus** [comment]
This is a known issue and will be fixed in 5.11.1 patch. 

To answer some more general questions. You are correct that this was an oversight when updating the headers that did not account for c++. "BUCK" is an open sourced build system used by Facebook. As far as this project goes you should never need to worry or think about it. I would definitely not add it to your project, you will generate a lot of confusion.
 
Your best bet is to tag to a previous version and update to 5.11.1 when it is released.

**Comment by joesus** [comment]
@georgi should be working now with 5.11.1

**Comment by kobyy** [comment]
Hi, I'm getting the same errors in 5.11.1

**Comment by joesus** [comment]
@kobyy please provide more information. It would help to know which file needs to include a check. Also would help to know how you are incorporating the sdk as there are a variety of ways to do this. Thanks!

**Comment by kobyy** [comment]
Hi, thanks for the response.
this is happening on: FBSDKLoginButton.h
error from Xcode:
/Users/user/Desktop/FacebookSDK/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginButton.h:24:1: Use of '@import' when modules are disabled

I basically downloaded 5.11.1 on GitHub, copied it to ~/Desktop/FacebookSDK  and then updated my search paths in project/build setting to point to ~/Desktop/FacebookSDK
not sure if there is another way? thanks

**Comment by benrui** [comment]
I'm using "facebook-unity-sdk-7.18.0" , and got exactly the same error:
--------

*/Pods/Headers/Public/FBSDKShareKit/FBSDKShareKit/FBSDKHashtag.h:24:1: error: use of '@import' when modules are disabled
@import FBSDKCoreKit;
^
*/Pods/Headers/Public/FBSDKShareKit/FBSDKShareKit/FBSDKHashtag.h:33:37: error: cannot find protocol declaration for 'FBSDKCopying'; did you mean 'NSCopying'?
@interface FBSDKHashtag : NSObject <FBSDKCopying, NSSecureCoding>
